line-length = 100

[format]
docstring-code-format = true

[lint]
select = ["ALL"]
ignore = [
    "D1",    # undocumented
    "D203",  # one blank line before class
    "D213",  # multi-line summary second line
    "D400",  # missing trailing period
    "D415",  # missing terminal punctuation
    "TD001", # invalid todo tag
    "TD002", # missing todo author
    "TD003", # missing todo link
    "TRY002", # raise vanilla class
    "TRY003", # raise vanilla args
    "TRY401", # verbose log message
    "BLE001", # blind except
    "G004",  # logging f string
    "RET504", # unnecessary assign
    "EM", # string/f-string/dot-format in exception
    "RUF002", # zenkaku
    "RUF003", # zenkaku
]
unfixable = [
    "F401", # unused import
    "F841", # unused variable
]

[lint.pycodestyle]
ignore-overlong-task-comments = true

[lint.per-file-ignores]
"mcp-server/src/main.py" = ["E501", "D417", "ARG001"]
"mcp-addin/**.py" = ["TID252", "N813"]
