[project]
name = "fusion-mcp-addin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "adsk>=2.0.12157",
]
